---
- name: My first playbook
  hosts: localhost
  connection: local
  tasks:
    - name: Create a folder on Desktop
      file:
        path: ~/Desktop/ansible-test
        state: directory

    - name: Create a text file inside it
      copy:
        content: "Ansible made this file!"
        dest: ~/Desktop/ansible-test/hello.txt