---
- name: My first playbook
  hosts: localhost
  connection: local
  tasks:
    - name: Create a folder on Desktop
      ansible.builtin.file:
        path: ~/GIT/ansible-test
        state: directory
        mode: '0755'

    - name: Create a text file inside it
      ansible.builtin.copy:
        content: "Ansible made this file!\n I made this change afterwords"
        dest: ~/GIT/ansible-test/hello.txt
        mode: '0644'



        